### ISSUE TITLE
Sampled images in examples have pixel errors

### ISSUE THREAD

**Issue by nikste** [LukasRinder/normalizing-flows#1]
how come, is there maybe still a bug in the implementation ?

**Comment by muratcankaracabey** [comment]
> how come, is there maybe still a bug in the implementation ?

Hi, we didn't use CNNs within the neural network architecture of the RealNVP and MAF implementations. In addition to some other differences such as lack of checkerboard masking, this also might have made our implementation a rather simplified version of the one that authors did. This might be the cause of less fancy samples we had.
