### ISSUE TITLE
shape_event not there in tensorflow.

### ISSUE THREAD

**Issue by StarKnight7** [LukasRinder/normalizing-flows#3]
I tried running the example_training.ipynb and I got the error as shown in the below pic. I request you to please tell me how to adapt this to the latest version in tensorflow.
![nf6_Lukas](https://user-images.githubusercontent.com/92370846/136948492-825ff12c-d877-4dc1-9ac0-0428d809ed55.png)

**Comment by awong655** [comment]
@StarKnight7 I ran into the same issue on Tensorflow-gpu 2.5.0. I was reading the tensorflow documentation on MAFs linked here: https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/MaskedAutoregressiveFlow.  

Here is the code that I used to create the MAF. 

`maf = tfd.TransformedDistribution(
    distribution=tfd.Sample(tfd.Normal(loc=0., scale=1.), sample_shape=[2]),
    bijector=bijector)`

The visual outputs and the sanity checks will confirm that this is correct. 
![image](https://user-images.githubusercontent.com/34189856/143782539-d7ddae9a-977a-44a3-9d9e-7e4c759bce4c.png)

**Comment by LukasRinder** [comment]
Sorry for my late reply!

I looked into the issue and @awong655's solution is correct. Tensorflow changed the API and the floating dependency broke the code. I fixed the bug and pinned dependencies in `requirements.txt` that worked for me (see #4). I used Python version 3.9.7.

You can install the dependencies via the following command.
```bash
pip install -r requirements.txt
```
